[백준] 2015. 수들의 합 4 문제풀이
Rain3321/algorithm_study pull request #102
Opened 2022-01-31 03:59 UTC by minwoo9629

`N×(N+1)/2`개의 부분합을 어떻게 구하면 좋을지 고민하며 시간이 많이....걸린 문제이다.
처음에 생각한 방법은 앞에서 만들어지는 경우의 수를 모두 저장해가며 문제를 풀이했다.
`2 -2 2 -2`일때 `index`는 1부터 시작한다고 하자.
첫번째 `2`에서 만들어지는 수는 `2` 두번째 `-2`까지 만들어지는 수는 `-2`(자기자신) `0`(앞의 2와 더함)
세번째 값 2에선 앞의 `0` `2` `2`(자기자신) 과 같이 점점 인덱스 개수 만큼 수가 만들어진다.
이와 같은 방법은 메모리초과가 일어났다.

너무 불필요하게 수를 하나하나 다 구하는 것이 아닌가 생각이 들어 `key`를 수 `value`를 갯수로 생각했다.
이렇게 하면 굳이 수를 다 저장하지않고 카운트만 더해주면 불필요한 메모리를 줄일 수 있을것이라 생각했다.

누적합을 구한뒤 누적합 값을 순회하며 `prefix[i]-k` 값이 해쉬맵에 존재하면 그에 따른 `value`값을 `result`에 더해주고 존재하지 않으면 `0`값을 더하도록하였다.

그리고 `result`의 자료형은 `N×(N+1)/2`개에서 `N`의 값이 `200000`이면 `int`의 범위를 초과하기 때문에 `long`자료형을 사용하였다.

2022-02-09 12:49 UTC, Rain3321 requested changes
고생하셨습니다.

2022-02-09 12:49 UTC, Rain3321 commented on minwoo.lee_java/src/BOJ2015.java
> +        prefix = new int[n + 1];
일반적으로 자바에서는 필요한 곳에서 변수를 선언하고 초기화를 합니다. 
구글의 자바 코딩 스타일 가이드에서도 이를 이야기합니다.
(https://google.github.io/styleguide/javaguide.html#s4.8.2-variable-declarations 중 4.8.2.2 Declared when needed 파트)
그래서 선언과 초기화를 같이 하는게 좋아 보입니다.

```suggestion
        int n = Integer.parseInt(st.nextToken());
        int k = Integer.parseInt(st.nextToken());
        long result = 0L;
        int[] nums = new int[n + 1];;
        int[] prefix = new int[n + 1]; 
```

2022-02-09 12:49 UTC, Rain3321 commented on minwoo.lee_java/src/BOJ2015.java
> +        numSums.put(0, 1);
이 값을 정해준 이유가 무엇인가요?

2022-02-09 14:18 UTC, minwoo9629 commented on minwoo.lee_java/src/BOJ2015.java
> +        numSums.put(0, 1);
누적합 값을 순회하며 `prefix[i]-k` 값이 해쉬맵에 존재하는지 확인하는데 문제에서 `k` 가 `0`일때
`prefix[i]` 자체가 `0`일때 카운트를 해야하므로 `numSums`에 `key` 가 0인 `value` 가 `1` 값을 넣어 주었습니다.

2022-02-09 14:30 UTC, Rain3321 commented on minwoo.lee_java/src/BOJ2015.java
> +        numSums.put(0, 1);
k가 0일 때 누접합이 0이라는 걸 아래 반복문에서 카운트 하는거 아닌가요?

2022-02-09 15:38 UTC, minwoo9629 commented on minwoo.lee_java/src/BOJ2015.java
> +        numSums.put(0, 1);
저는 처음에 누적합  `prefixSum`을 구할 때 `0`나오면 바로 카운트를 올리지 않습니다.
그렇기 때문에 누적합이 자체가 `0`인 경우의 카운트 증가를 위해 `numSums.put(0, 1)`를 사용한 것입니다.

2022-02-10 13:39 UTC, Rain3321 approved these changes
수고하셨습니다.

2022-02-10 13:40 UTC, merged