[python] BJ9084 풀이
Rain3321/algorithm_study pull request #20
Opened 2021-08-24 09:40 UTC by minwoo9629

## 문제 접근 방법

- 동전들을 가지고 주어진 값을 만드는 경우의 수를 구해야 하는데 `dp[n]` 을 값 `n`을 만드는데 모든 방법의 수로 생각하고 시작했다.
- 이중 `for`문으로 첫번째 `for`는 동전의 종류 두번째 `for`는 `1~주어진 값`을 범위로 하였다.
- `price` 값이 `coin`보다 크면 값을 만들 수 있다는 `if`조건을 작성하였다.
- 해당 `dp[price]` 는 `price - coin`의 종류를 더해준다.
- 맨 처음 해당 동전 하나로 만들 수 있는 경우의 수는 1이므로 dp[price]` 는 `price - coin`이 되도록 `dp[0] =1`로 하였다.
- 시간 `112ms`

2021-08-24 13:20 UTC, Rain3321 commented
이 브랜치 커밋 수정해주세요 브랜치는 9084 번 문제 풀이인데 18352번 문제풀이도 같이 올라와있네요.
확인해서 메인을 기준으로 1개 커밋만 올라올 수 있도록 해주세요

2021-08-24 13:36 UTC, Rain3321 commented
> * 맨 처음 해당 동전 하나로 만들 수 있는 경우의 수는 1이므로 dp[price]`는`price - coin`이 되도록 `dp[0] =1`로 하였다.

이 부분도 백틱(`) 문제가 있는 것 같습니다. 다시 한번 확인해주세요.
그리고 기저 조건인 dp[0]=1가 되는 이유가 조금 이상한 듯 싶습니다. 금액이 0인데 동전 하나로 만들 수 있는 경우의 수가 1인가요?

2021-08-24 14:09 UTC, minwoo9629 commented
어... 브랜치 수정 해보겠습니다.....
문제에서 사실 0인 상황은 주어지지 않으나 생각해보면 0이란 금액은 모든 동전을 사용하지 않는 경우이기 때문에 한 가지 밖에 나오지 않기때문에 `dp[0]=1`이다!

2021-09-01 11:47 UTC, Rain3321 requested changes
현재 브랜치에서 이전 문제에 대한 커밋을 아에 없애고 main에서 pull --rebase 받은걸 현재 브랜치에 다시 리베이스 한 이후에 push -f 하시면 커밋 정리가 될꺼에요

2021-09-02 13:43 UTC, merged