[백준] 15787. 기차가 어둠을 헤치고 은하수를 문제풀이
Rain3321/algorithm_study pull request #87
Opened 2022-01-17 14:19 UTC by minwoo9629

일단 명령의 종류 `command` 기차 번호 `train` 그리고 자리의 번호인 `seat` 값을 받습니다.
하지만 `command`가 `3`이나 `4`인 경우는 `seat` 값이 존재하지 않아 오류가 발생합니다.
따라서 `try catch`를 사용하여 예외처리를 해주면 되겠다고 생각했습니다.

기차의 좌석의 표현은 `char`형 이차원 배열로 표현하도록 하였습니다.
상위 차원은 기차의 번호 하위 차원은 좌석번호를 뜻합니다.

이제 각 명령에 대하여 `command` 메소드가 실행됩니다.
그리고 좌석이동이 끝나면 각 행마다 `char`형을 합쳐서 하나의 문자열로 만들었습니다.
이제 만들어진 문자열 중 중복을 제외한 개수를 출력해야했습니다.

처음엔 `Set` 자료형 인터페이스를 구현한 `HashSet`을 사용하였습니다.
`HashSet`에 값을 저장하면 중복되어 저장이 되지 않기 때문입니다.

하지만 아직 `HashSet`에 대해 정확히 모르고 있어 문제를 풀기만을 위해 코드를 쓴건 아닌가 라는 생각을 했고 그래서 아는 방식선에서 어떻게 개수를 맞게 출력할 수 있을지 고민했습니다.

그래서 `ArrayList`를 사용하여 해당 `ArrayList`에 문자열이 존재하지 않으면 `ArrayList`에 값을 더해주는
방식으로 중복을 제거하고 마지막으로 `ArrayList`의 크기를 출력해서 값을 구했습니다.

2022-01-18 00:13 UTC, Rain3321 requested changes
단순 문제 풀이만을 생각하면 상관없지만 코드의 품질을 생각해 보았을 때 수정해야할 부분이 많아 보입니다.
수정 부탁드립니다.

2022-01-18 00:13 UTC, Rain3321 commented on minwoo.lee_java/src/BOJ15787.java
> +        }
로직의 문제는 없어 보이지만 더 깔끔하게 짤 수 있을 것 같습니다.
코드를 보면서 든 의문점이 있습니다.

1. 1command 가 1 일 때 자리가 비어있으면 자리에 앉고 비어있지 않으면 아무 행동도 취하지 않습니다.
 이 말은 `if (command == 1 && trains[train - 1][seat - 1] == '0')` 의 조건문에서 정리 될 수 있는 것이 있다는 말과 일맥상통합니다. 이 조건문을 좀더 정리해주세요.

2. trains 배열을 char 배열로 한 이유가 궁금합니다.

3. else 문 안에만 return 이 있는 이유가 궁금합니다.

4. else 문 안에 왜 다시 `if (command == 4)` 조건문이 존재하나요?

2022-01-18 00:13 UTC, Rain3321 commented on minwoo.lee_java/src/BOJ15787.java
> +}
github에서 코드의 마지막 줄에 개행이 없으면 이렇게 경고를 띄우고 있습니다.
항상 코드의 마지막 줄은 개행을 넣어주세요.

intellij 의 경우 자동으로 개행이 들어가게 할 수 있습니다.
[링크](https://johngrib.github.io/wiki/intellij/#%ED%8C%8C%EC%9D%BC-%EB%A7%88%EC%A7%80%EB%A7%89%EC%97%90-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-1%EA%B0%9C%EC%9D%98-%EA%B0%9C%ED%96%89-%EB%AC%B8%EC%9E%90-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0)

2022-01-18 00:13 UTC, Rain3321 commented on minwoo.lee_java/src/BOJ15787.java
> +        ArrayList<String> arr = new ArrayList<>();
고민해봤으면 좋겠습니다. 지금 당장 모른다고 사용을 하지 않는 것은 좋아보이지 않습니다.
이미 python 을 통해 set이 어떤 동작을 하는지 알고 있는 상태에서도 단순히 HashSet 을 모른다고 사용하지 않는다는 것은 "이번 문제 풀이를 하기 위해 찾아보지 않겠다"라는 생각과 비슷해보입니다.

HashSet 을 찾아보고 문제에 적용해보세요.

2022-01-18 15:48 UTC, minwoo9629 commented on minwoo.lee_java/src/BOJ15787.java
> +        }
1. 고민 후 수정해보겠습니다.
2. 최종 열차에 승객이 탄모습을 `ex) 0000001` 일때 이를 하나의 문자열로 생각하기위해
배열을 `char`을 해야겠다고 생각했습니다.
또한 최대 기차의 수가 `100000`일때 `char`을 사용하면 `4000KB`로 메모리초과가 일어나지 않을 것이라 생각했습니다.
3. 지우는 것을 누락했습니다.
4. `command == 1 && trains[train - 1][seat - 1] == '0'`라는 좋지 않은 조건 때문에
`commnd` 값이 `1`이여도 자리가 1이면 해당 `if`가 돌기 때문에 결국 `else`만
적은경우 `command` 1일때도 실행될 수 있기에 `else` 이후 추가적인 `if`문을 사용하였습니다. 해당 부분도 1번을 고민하면서 수정하겠습니다.

2022-01-18 15:48 UTC, minwoo9629 commented on minwoo.lee_java/src/BOJ15787.java
> +}
적용하였습니다.

2022-01-18 15:51 UTC, minwoo9629 commented on minwoo.lee_java/src/BOJ15787.java
> +        ArrayList<String> arr = new ArrayList<>();
처음에 `HashSet`을 이용했는데 위에 언급한 이유로 사용하지 않았습니다.
하지만 `"이번 문제 풀이를 하기 위해 찾아보지 않겠다"라는 생각과 비슷해보입니다.`라는
말처럼 알고리즘 문제를 푸는 행위가 그 속에서도 새로운 자료구조나 모르는 것을 공부하는 것이기 때문에 충분히 학습후에 적용해서 수정해보겠습니다.

2022-01-18 16:28 UTC, minwoo9629 commented
`Java`의 `Collection`은 데이터의 집합 의미합니다. 그리고 `Collection`에는 집합처럼 중복되지 않는 원소들의 모음을 만들 수 있는`Set`이라는 자료구조가 있습니다.

`HashSet`은 데이터 저장을 `Hash  Table` 구조를 이용하는 `HashMap`을 이용하여 만들어 집니다.
`Map`에서 중복 `key`는 존재할 수 없다는 점을 이용하여, `key`를 `set`의 값으로 `value`에는 더미 `Object`를 저장 방식으로 데이터를 추가합니다.
이렇게 중복 값이 존재하지 않으므로 각 기차마다의 `char`배열을 문자열로 바꾸어 저장합니다.
그리고 `HashSet`의 크기를 출력하여 답을 구합니다.

`Hash Table`의 동작 방식과 `TreeSet`은 추가로 공부하여 `Notion`에 정리하도록 하겠습니다.

2022-01-19 00:05 UTC, Rain3321 approved these changes
코드가 훨씬 깔끔해졌네요. 고생하셨습니다.

2022-01-19 01:01 UTC, merged